# **Algoritmos de Ordenação**

In [1]:
# Importação
import random
import numpy as np

## Bubble Sort

In [2]:
# função do bubble sort
def bubble_sort(vetor):
    n = len(vetor)

    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor[j + 1]:
                temp = vetor[j]
                vetor[j] = vetor[j + 1]
                vetor[j + 1] = temp
    return vetor

In [3]:
# Testando a função
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [4]:
# Testando a função
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selection Sort

In [5]:
# Função Selection Sort
def selection_sort(vetor):
    n = len(vetor)

    for i in range(n):
        id_minimo = i
        for j in range(i + 1, n):
            if vetor[id_minimo] > vetor[j]:
                id_minimo = j
        temp = vetor[i]
        vetor[i] = vetor[id_minimo]
        vetor[id_minimo] = temp
    return vetor

In [6]:
# Testando a função
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [7]:
# Testando a função
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Insertion Sort

In [8]:
# função de insertion sort
def insertion_sort(vetor):
    n = len(vetor)

    for i in range(1, n):
        marcado = vetor[i]

        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j + 1] = vetor[j]
            j -= 1
        vetor[j + 1] = marcado
    return vetor

In [9]:
# Testando a função
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [10]:
# Testando a função
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Shell Sort

In [11]:
# Função de shell sort
def shell_sort(vetor):
    intervalo = len(vetor) // 2

    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2
    return vetor

In [12]:
# Testando a função
shell_sort(np.array([8,5,1,4,2,3]))

array([1, 2, 3, 4, 5, 8])

In [13]:
# Testando a função
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [14]:
# Testando a função
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Merge Sort

In [15]:
# Função de Merge sort
def merge_sort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao].copy()
        direita = vetor[divisao:].copy()

        merge_sort(esquerda)
        merge_sort(direita)

        i = j = k = 0
        # Ordena esquerda e direita
        while i < len(esquerda) and j < len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita[j]
                j += 1
            k +=1

        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1

    return vetor

In [16]:
# Testando a função
merge_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [17]:
# Testando a função
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Quick Sort

In [18]:
# Função de Partição
def particao(vetor, inicio, final):
    pivo = vetor[final]
    i = inicio - 1

    for j in range(inicio, final):
        if vetor[j] <= pivo:
            i += 1
            vetor[i], vetor[j] = vetor[j], vetor[i]
    vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
    return i + 1

# Função Quick Sort
def quick_sort(vetor, inicio, final):
    if inicio < final:
        posicao = particao(vetor, inicio, final)
        # Esquerda
        quick_sort(vetor, inicio, posicao - 1)
        # Direito
        quick_sort(vetor, posicao + 1, final)
    return vetor

In [19]:
# Testando a função
vetor = np.array([15, 34, 8, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])

In [20]:
# Testando a função
vetor = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Exercício: comparativo entre algoritmos

In [21]:
# Vetor
vetor_float = np.random.rand(5000)

In [22]:
# Testando a função
bubble_sort(vetor_float.copy())

array([3.52544486e-05, 7.21966538e-05, 2.37689208e-04, ...,
       9.98804157e-01, 9.98897800e-01, 9.99169756e-01])

In [23]:
# Tempo
%timeit bubble_sort(vetor_float.copy())

5.73 s ± 679 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
# Testando a função
selection_sort(vetor_float.copy())

array([3.52544486e-05, 7.21966538e-05, 2.37689208e-04, ...,
       9.98804157e-01, 9.98897800e-01, 9.99169756e-01])

In [25]:
# Tempo
%timeit selection_sort(vetor_float.copy())

3.18 s ± 71.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
# Testando a função
insertion_sort(vetor_float.copy())

array([3.52544486e-05, 7.21966538e-05, 2.37689208e-04, ...,
       9.98804157e-01, 9.98897800e-01, 9.99169756e-01])

In [27]:
# Tempo
%timeit insertion_sort(vetor_float.copy())

2.45 s ± 75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
# Testando a função
shell_sort(vetor_float.copy())

array([3.52544486e-05, 7.21966538e-05, 2.37689208e-04, ...,
       9.98804157e-01, 9.98897800e-01, 9.99169756e-01])

In [29]:
# Tempo
%timeit shell_sort(vetor_float.copy())

51.1 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
# Testando a função
merge_sort(vetor_float.copy())

array([3.52544486e-05, 7.21966538e-05, 2.37689208e-04, ...,
       9.98804157e-01, 9.98897800e-01, 9.99169756e-01])

In [31]:
# Tempo
%timeit merge_sort(vetor_float.copy())

45.2 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
# Testando a função
quick_sort(vetor_float.copy(), 0, len(vetor) - 1)

array([0.16009814, 0.25323311, 0.29501065, ..., 0.79709902, 0.65484547,
       0.22537607])

In [33]:
# Tempo
%timeit quick_sort(vetor_float.copy(), 0, len(vetor) - 1)

19.2 µs ± 2.68 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
