# **Algoritmos de Ordenação**

In [1]:
# Importação
import numpy as np

## Bubble Sort

In [2]:
# função do bubble sort
def bubble_sort(vetor):
    n = len(vetor)

    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor[j + 1]:
                temp = vetor[j]
                vetor[j] = vetor[j + 1]
                vetor[j + 1] = temp
    return vetor

In [3]:
# Testando a função
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [4]:
# Testando a função
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selection Sort

In [5]:
# Função Selection Sort
def selection_sort(vetor):
    n = len(vetor)

    for i in range(n):
        id_minimo = i
        for j in range(i + 1, n):
            if vetor[id_minimo] > vetor[j]:
                id_minimo = j
        temp = vetor[i]
        vetor[i] = vetor[id_minimo]
        vetor[id_minimo] = temp
    return vetor

In [6]:
# Testando a função
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [7]:
# Testando a função
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Insertion Sort

In [8]:
# função de insertion sort
def insertion_sort(vetor):
    n = len(vetor)

    for i in range(1, n):
        marcado = vetor[i]

        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j + 1] = vetor[j]
            j -= 1
        vetor[j + 1] = marcado
    return vetor

In [9]:
# Testando a função
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [10]:
# Testando a função
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Shell Sort

In [11]:
# Função de shell sort
def shell_sort(vetor):
    intervalo = len(vetor) // 2

    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2
    return vetor

In [12]:
# Testando a função
shell_sort(np.array([8,5,1,4,2,3]))

array([1, 2, 3, 4, 5, 8])

In [13]:
# Testando a função
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [14]:
# Testando a função
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])