# **Caminho mais curso com o Algoritmo de Dijkstra**

## Estrutura do Grafo - Matriz de Adjacência

In [1]:
# Importação
import numpy as np

In [2]:
# Criando os Vertices
vertices = {
    'arad': 0, 'zerind': 1, 'oradea': 2, 'sibiu': 3, 'timisoara': 4,
    'lugoj': 5, 'mehadia': 6, 'dobreta': 7, 'craiova': 8, 'rimnicu': 9,
    'fagaras': 10, 'pitesti': 11, 'bucharest': 12, 'giurgiu': 13
}

In [3]:
# Visualizando o valores
vertices['arad'], vertices['pitesti'], vertices['lugoj']

(0, 11, 5)

In [4]:
# Tamanho
len(vertices)

14

In [5]:
# Criando o dicionario de cidade
cidades = {
    0: 'arad', 1: 'zerind', 2: 'oradea', 3: 'sibiu', 4: 'timisoara',
    5: 'lugoj', 6: 'mehadia', 7: 'dobreta', 8: 'craiova', 9: 'rimnicu',
    10: 'fagaras', 11: 'pitesti', 12: 'bucharest', 13: 'giurgiu'
}

In [6]:
# Visualizando
cidades[0], cidades[12]

('arad', 'bucharest')

In [7]:
# Criando as arestas
arestas = np.zeros([len(cidades), len(cidades)], dtype=int)

In [8]:
# Tamanho
arestas.shape

(14, 14)

In [9]:
# Visualizando arestas
arestas

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
# A distancia
vertices['arad'], vertices['zerind'], vertices['sibiu'], vertices['timisoara']

(0, 1, 3, 4)

In [11]:
# Adicionado a distancia ao vértice
arestas[vertices['arad'], [vertices['zerind']]] = 75
arestas[vertices['arad'], [vertices['sibiu']]] = 140
arestas[vertices['arad'], [vertices['timisoara']]] = 118
arestas[vertices['zerind'],[vertices['arad']]] = 75
arestas[vertices['zerind'],[vertices['oradea']]] = 71

arestas[vertices['oradea'],[vertices['zerind']]] = 71
arestas[vertices['oradea'],[vertices['sibiu']]] = 151

arestas[vertices['sibiu'],[vertices['oradea']]] = 151
arestas[vertices['sibiu'],[vertices['arad']]] = 140
arestas[vertices['sibiu'],[vertices['fagaras']]] = 99
arestas[vertices['sibiu'],[vertices['rimnicu']]] = 80

arestas[vertices['timisoara'],[vertices['arad']]] = 118
arestas[vertices['timisoara'],[vertices['lugoj']]] = 111

arestas[vertices['lugoj'],[vertices['timisoara']]] = 111
arestas[vertices['lugoj'],[vertices['mehadia']]] = 70

arestas[vertices['mehadia'],[vertices['lugoj']]] = 70
arestas[vertices['mehadia'],[vertices['dobreta']]] = 75

arestas[vertices['dobreta'],[vertices['mehadia']]] = 75
arestas[vertices['dobreta'],[vertices['craiova']]] = 120

arestas[vertices['craiova'],[vertices['dobreta']]] = 120
arestas[vertices['craiova'],[vertices['pitesti']]] = 138
arestas[vertices['craiova'],[vertices['rimnicu']]] = 146

arestas[vertices['rimnicu'],[vertices['craiova']]] = 146
arestas[vertices['rimnicu'],[vertices['sibiu']]] = 80
arestas[vertices['rimnicu'],[vertices['pitesti']]] = 97

arestas[vertices['fagaras'],[vertices['sibiu']]] = 99
arestas[vertices['fagaras'],[vertices['bucharest']]] = 211

arestas[vertices['pitesti'],[vertices['rimnicu']]] = 97
arestas[vertices['pitesti'],[vertices['craiova']]] = 138
arestas[vertices['pitesti'],[vertices['bucharest']]] = 101

arestas[vertices['bucharest'],[vertices['fagaras']]] = 211
arestas[vertices['bucharest'],[vertices['pitesti']]] = 101
arestas[vertices['bucharest'],[vertices['giurgiu']]] = 90

In [12]:
# Visualizando as arestas
arestas

array([[  0,  75,   0, 140, 118,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [ 75,   0,  71,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,  71,   0, 151,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [140,   0, 151,   0,   0,   0,   0,   0,   0,  80,  99,   0,   0,
          0],
       [118,   0,   0,   0,   0, 111,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0, 111,   0,  70,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,  70,   0,  75,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,  75,   0, 120,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0, 120,   0, 146,   0, 138,   0,
          0],
       [  0,   0,   0,  80,   0,   0,   0,   0, 146,   0,   0,  97,   0,
          0],
       [  0,   0,   0,  99,   0,   0,   0,   0,   0,   0,   0,   0, 211,
          0],
       [  0,   0,   0,   0,   0,   0,   0, 

In [13]:
# A distancia
arestas[vertices['pitesti'],[vertices['rimnicu']]]

array([97])

In [14]:
# Distancia
arestas[vertices['arad'],[vertices['sibiu']]]

array([140])

## Algoritmo de Dijkstra

In [15]:
# Crianção da Classe
import sys
class Dijkstra:
    def __init__(self, vertices, arestas, inicio):
        self.tamanho = len(vertices)
        self.vertices = vertices
        self.grafo = arestas
        self.inicio = inicio

    def mostra_solucao(self, distancias):
        print(f'Menores distâncias de {self.vertices[self.inicio]} até todos os outros')
        for vertice in range(self.tamanho):
            print(self.vertices[vertice], distancias[vertice])

    def distancia_minima(self, distancia, visitados):
        minimo = sys.maxsize
        for vertice in range(self.tamanho):
            if distancia[vertice] < minimo and visitados[vertice] == False:
                minimo = distancia[vertice]
                indice_minimo = vertice
        return indice_minimo

    def dijkstra(self):
        distancia = [sys.maxsize] * self.tamanho
        distancia[self.inicio] = 0
        visitados = [False] * self.tamanho

        for _ in range(self.tamanho):
            indice_minimo = self.distancia_minima(distancia, visitados)
            visitados[indice_minimo] = True
            for vertice in range(self.tamanho):
                if self.grafo[indice_minimo][vertice] > 0 and visitados[vertice] == False \
                    and distancia[vertice] > distancia[indice_minimo] + self.grafo[indice_minimo][vertice]:
                    distancia[vertice] = distancia[indice_minimo] + self.grafo[indice_minimo][vertice]

        self.mostra_solucao(distancia)

In [16]:
# Testando a classe 
dijkstra = Dijkstra(cidades, arestas, vertices['arad'])
dijkstra.dijkstra()

Menores distâncias de arad até todos os outros
arad 0
zerind 75
oradea 146
sibiu 140
timisoara 118
lugoj 229
mehadia 299
dobreta 374
craiova 366
rimnicu 220
fagaras 239
pitesti 317
bucharest 418
giurgiu 508
